name: Build

on: [pull_request]

jobs:
  check:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v3'
        with:
          cache: 'yarn'
          node-version: 'lts/*'

      - name: 'Install the Node.js dependencies'
        run: 'yarn install --immutable'

      - name: 'Build the project'
        run: 'yarn build'
