name: Linter

on: [pull_request]

jobs:
  check:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v3'
        with:
          cache: 'yarn'
          node-version: 'lts/*'

      - name: 'Install the Node.js dependencies'
        run: 'yarn install --immutable'

      - name: 'Lint the project'
        run: 'yarn lint'

      - name: 'Add lint summary'
        run: |
          echo "## Lint" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
